## 1-) Data Explorer

In [188]:
import pandas as pd

In [189]:
df=pd.read_csv('../data/raw_data.csv')

In [190]:
df.head()

,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,...,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.715,87.917,4,acoustic
1,1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,...,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.267,77.489,4,acoustic
2,2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,...,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.120,76.332,4,acoustic
3,3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,...,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.143,181.740,3,acoustic
4,4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,...,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.167,119.949,4,acoustic

In [191]:
df.shape

(114000, 21)

In [192]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 114000 entries, 0 to 113999
Data columns (total 21 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Unnamed: 0        114000 non-null  int64
 1   track_id          114000 non-null  object
 2   artists           113999 non-null  object
 3   album_name        113999 non-null  object
 4   track_name        113999 non-null  object
 5   popularity        114000 non-null  int64
 6   duration_ms       114000 non-null  int64
 7   explicit          114000 non-null  bool
 8   danceability      114000 non-null  float64
 9   energy            114000 non-null  float64
 10  key               114000 non-null  int64
 11  loudness          114000 non-null  float64
 12  mode              114000 non-null  int64
 13  speechiness       114000 non-null  float64
 14  acousticness      114000 non-null  float64
 15  instrumentalness  114000 non-null  float64
 16  liveness          114000 non-null  float64
 17  valence           114000 non-null  float64
 18  tempo             114000 non-null  float64
 19  time_signature    114000 non-null  int64
 20  track_genre       114000 non-null  object
dtypes: bool(1), float64(9), int64(6), object(5)
memory usage: 17.5+ MB

## 2-) Data Clean

In [193]:
df=df.drop(columns=['Unnamed: 0','track_id'])
df

,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,1,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.7150,87.917,4,acoustic
1,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,1,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.2670,77.489,4,acoustic
2,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,0,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.1200,76.332,4,acoustic
3,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,0,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.1430,181.740,3,acoustic
4,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,2,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.1670,119.949,4,acoustic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113995,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Sleep My Little Boy,21,384999,False,0.172,0.2350,5,-16.393,1,0.0422,0.6400,0.928000,0.0863,0.0339,125.995,5,world-music
113996,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Water Into Light,22,385000,False,0.174,0.1170,0,-18.318,0,0.0401,0.9940,0.976000,0.1050,0.0350,85.239,4,world-music
113997,Cesária Evora,Best Of,Miss Perfumado,22,271466,False,0.629,0.3290,0,-10.895,0,0.0420,0.8670,0.000000,0.0839,0.7430,132.378,4,world-music
113998,Michael W. Smith,Change Your World,Friends,41,283893,False,0.587,0.5060,7,-10.889,1,0.0297,0.3810,0.000000,0.2700,0.4130,135.960,4,world-music
113999,Cesária Evora,Miss Perfumado,Barbincor,22,241826,False,0.526,0.4870,1,-10.204,0,0.0725,0.6810,0.000000,0.0893,0.7080,79.198,4,world-music

In [194]:
df.isna().sum()

artists             1
album_name          1
track_name          1
popularity          0
duration_ms         0
explicit            0
danceability        0
energy              0
key                 0
loudness            0
mode                0
speechiness         0
acousticness        0
instrumentalness    0
liveness            0
valence             0
tempo               0
time_signature      0
track_genre         0
dtype: int64

In [195]:
df=df.dropna()

In [196]:
df.isna().sum()

artists             0
album_name          0
track_name          0
popularity          0
duration_ms         0
explicit            0
danceability        0
energy              0
key                 0
loudness            0
mode                0
speechiness         0
acousticness        0
instrumentalness    0
liveness            0
valence             0
tempo               0
time_signature      0
track_genre         0
dtype: int64

In [197]:
df.duplicated().sum()

577

In [198]:
df=df.drop_duplicates()

In [199]:
df.duplicated().sum()

0

In [200]:
df = df[(df['popularity'] >= 0) & (df['popularity'] <= 100)]

In [201]:
df['artists'] = df['artists'].str.strip().str.title()

In [202]:
df['track_genre'] = df['track_genre'].str.strip().str.lower()

In [203]:
df['artists'] = df['artists'].str.split(';')
df = df.explode('artists')

In [204]:
df.head()

,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,1,-6.746,0,0.1430,0.0322,0.000001,0.358,0.715,87.917,4,acoustic
1,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,1,-17.235,1,0.0763,0.9240,0.000006,0.101,0.267,77.489,4,acoustic
2,Ingrid Michaelson,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,0,-9.734,1,0.0557,0.2100,0.000000,0.117,0.120,76.332,4,acoustic
2,Zayn,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,0,-9.734,1,0.0557,0.2100,0.000000,0.117,0.120,76.332,4,acoustic
3,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,0,-18.515,1,0.0363,0.9050,0.000071,0.132,0.143,181.740,3,acoustic

## 3-) Feature Engineering

In [205]:
df['duration_min'] = df['duration_ms'] / (1000 * 60)

In [206]:
df = df[df['duration_min'] < 15]

In [207]:
def popularity_level(x):
    if x < 30:
        return 'Low'
    elif x < 70:
        return 'Medium'
    else:
        return 'High'

df['popularity_level'] = df['popularity'].apply(popularity_level)

In [208]:
df['duration_category'] = pd.cut(
    df['duration_min'],
    bins=[0,2,4,6,20],
    labels=['Very Short','Short','Medium','Long']
)
df['duration_category']

0          Short
1          Short
2          Short
2          Short
3          Short
           ...
113995      Long
113996      Long
113997    Medium
113998    Medium
113999    Medium
Name: duration_category, Length: 157162, dtype: category
Categories (4, object): ['Very Short' < 'Short' < 'Medium' < 'Long']

In [209]:
df['tempo_category'] = pd.cut(
    df['tempo'],
    bins=[0,90,120,150,250],
    labels=['Slow','Moderate','Fast','Very Fast']
)
df['tempo_category']

0              Slow
1              Slow
2              Slow
2              Slow
3         Very Fast
            ...
113995         Fast
113996         Slow
113997         Fast
113998         Fast
113999         Slow
Name: tempo_category, Length: 157162, dtype: category
Categories (4, object): ['Slow' < 'Moderate' < 'Fast' < 'Very Fast']

In [210]:
df['engagement_score'] = (
    df['energy'] +
    df['danceability'] +
    df['valence']
) / 3
df['engagement_score']

0         0.617333
1         0.284333
2         0.305667
2         0.305667
3         0.156200
            ...
113995    0.146967
113996    0.108667
113997    0.567000
113998    0.502000
113999    0.573667
Name: engagement_score, Length: 157162, dtype: float64

In [211]:
df['loudness_level'] = pd.cut(
    df['loudness'],
    bins=4,
    labels=['Low','Medium','High','Very High']
)
df['loudness_level']

0         Very High
1              High
2              High
2              High
3              High
            ...
113995         High
113996         High
113997         High
113998         High
113999         High
Name: loudness_level, Length: 157162, dtype: category
Categories (4, object): ['Low' < 'Medium' < 'High' < 'Very High']

In [212]:
df['explicit_label'] = df['explicit'].map({
    True: 'Explicit',
    False: 'Non-Explicit'
})
df['explicit_label']

0         Non-Explicit
1         Non-Explicit
2         Non-Explicit
2         Non-Explicit
3         Non-Explicit
              ...
113995    Non-Explicit
113996    Non-Explicit
113997    Non-Explicit
113998    Non-Explicit
113999    Non-Explicit
Name: explicit_label, Length: 157162, dtype: object

In [213]:
df['mood_score'] = (df['valence'] + df['energy']) / 2
df['mood_score']

0         0.58800
1         0.21650
2         0.23950
2         0.23950
3         0.10130
           ...
113995    0.13445
113996    0.07600
113997    0.53600
113998    0.45950
113999    0.59750
Name: mood_score, Length: 157162, dtype: float64

In [214]:
artist_counts = df['artists'].value_counts()
df['artist_song_count'] = df['artists'].map(artist_counts)
df['artist_song_count']

0         10
1         13
2         12
2         12
3         22
          ..
113995     4
113996     4
113997    16
113998    38
113999    16
Name: artist_song_count, Length: 157162, dtype: int64

In [215]:
genre_rank = df.groupby('track_genre')['popularity'].mean().rank(ascending=False)
df['genre_rank'] = df['track_genre'].map(genre_rank)
df['genre_rank']

0         23.0
1         23.0
2         23.0
2         23.0
3         23.0
          ...
113995    21.0
113996    21.0
113997    21.0
113998    21.0
113999    21.0
Name: genre_rank, Length: 157162, dtype: float64

In [216]:
df.columns

Index(['artists', 'album_name', 'track_name', 'popularity', 'duration_ms',
       'explicit', 'danceability', 'energy', 'key', 'loudness', 'mode',
       'speechiness', 'acousticness', 'instrumentalness', 'liveness',
       'valence', 'tempo', 'time_signature', 'track_genre', 'duration_min',
       'popularity_level', 'duration_category', 'tempo_category',
       'engagement_score', 'loudness_level', 'explicit_label', 'mood_score',
       'artist_song_count', 'genre_rank'],
      dtype='object')

In [ ]:
#df.to_csv("data_preprocessed.csv", index=False)